version: "3"

services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    restart: always
    volumes:
      - postgres_volume:$PGDATA
    command: -p $POSTGRES_PORT
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  postgres_volume:
