version: "3"

services:
  postgres:
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_db
    ports:
      - 8888:8888
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    command: -p 8888
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  postgres_volume:
